Update composer.lock
Fixed bug in CI:
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing hirak/prestissimo (0.3.10): Downloading (connecting...)Downloading (0%)           Downloading (35%)Downloading (70%)Downloading (100%)
Package hirak/prestissimo is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files
./composer.json is valid, but with a few warnings
See https://getcomposer.org/doc/04-schema.md for details on the schema
The lock file is not up to date with the latest changes in composer.json, it is recommended that you run `composer update` or `composer update <package name>`.
License "GPL-3.0" is a deprecated SPDX license identifier, use "GPL-3.0-only" or "GPL-3.0-or-later" instead
require.doctrine/orm : exact version constraints (2.7.0) should be avoided if the package follows semantic versioning
require.mrclay/minify : exact version constraints (2.2.0) should be avoided if the package follows semantic versioning
Error: Process completed with exit code 2.