Replace create_function with anonymous function
As per the php docs, create_function creates a function in the outer scope, with each call. So with large CSV imports, it creates a case where thousands of functions gets created, causing the error

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /var/www/html/app/bundles/LeadBundle/Model/LeadModel.php(1884) : runtime-created function on line 1

To keep everything consistent, I removed the string and added the code as an exact match, so there shouldn't be any errors from this commit. Although the "InputHelper::clean" function should be looked at considering it's not being passed by reference